const BOARD_ROWS = 14;
const BOARD_COLS = 37;

export const DIMENSIONS = [BOARD_ROWS, BOARD_COLS];

const MOBILE_BOARD_ROWS = 22;
const MOBILE_BOARD_COLS = 16;

export const MOBILE_DIMENSIONS = [MOBILE_BOARD_ROWS, MOBILE_BOARD_COLS];
